# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('sid', models.BigIntegerField()),
                ('phone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('agency', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.BigIntegerField()),
                ('aid', models.BigIntegerField()),
                ('city', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=1024)),
                ('cdate', models.CharField(max_length=1024)),
                ('pfee', models.CharField(max_length=1024)),
                ('pcompany', models.CharField(max_length=1024)),
                ('ccompany', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.BigIntegerField()),
                ('cid', models.BigIntegerField()),
                ('aid', models.BigIntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('style', models.CharField(max_length=1024)),
                ('deco', models.CharField(max_length=1024)),
                ('dir', models.CharField(max_length=1024)),
                ('stair', models.CharField(max_length=1024)),
                ('update', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=1024)),
                ('area', models.CharField(max_length=1024)),
                ('cost', models.CharField(max_length=1024)),
                ('phash', models.CharField(max_length=1024)),
                ('pdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('url', models.TextField()),
                ('aurl', models.TextField()),
                ('curl', models.TextField()),
                ('cm_list', models.CharField(max_length=255)),
                ('cm_id', models.CharField(max_length=255)),
                ('cm_lastpage', models.CharField(max_length=255)),
                ('cm_total', models.CharField(max_length=255)),
                ('cm_name', models.CharField(max_length=255)),
                ('cm_type', models.CharField(max_length=255)),
                ('cm_addr', models.CharField(max_length=255)),
                ('cm_cdate', models.CharField(max_length=255)),
                ('cm_pfee', models.CharField(max_length=255)),
                ('cm_pcom', models.CharField(max_length=255)),
                ('cm_ccom', models.CharField(max_length=255)),
                ('hs_list', models.CharField(max_length=255)),
                ('hs_lastpage', models.CharField(max_length=255)),
                ('ag_phone', models.CharField(max_length=255)),
                ('ag_name', models.CharField(max_length=255)),
                ('ag_agency', models.CharField(max_length=255)),
                ('hs_name', models.CharField(max_length=255)),
                ('hs_style', models.CharField(max_length=255)),
                ('hs_deco', models.CharField(max_length=255)),
                ('hs_dir', models.CharField(max_length=255)),
                ('hs_stair', models.CharField(max_length=255)),
                ('hs_update', models.CharField(max_length=255)),
                ('hs_type', models.CharField(max_length=255)),
                ('hs_area', models.CharField(max_length=255)),
                ('hs_cost', models.CharField(max_length=255)),
                ('hs_phash', models.CharField(max_length=255)),
            ],
        ),
    ]
